name: xeus-javascript
channels:
  - conda-forge
dependencies:
  - xeus-javascript
  - notebook
  - ipywidgets>=7.6
  - jupyterlab=3
  - jupyterlite-javascript-kernel==0.3.0
  - jupyterlite-pyodide-kernel==0.4.0b0
